version: '3'
services:
  cypress-chrome:
    image: cypress/included:9.7.0
    environment:
      - CYPRESS_BROWSER=chrome
    volumes:
      - ./:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run", "--browser", "chrome"]

  cypress-firefox:
    image: cypress/included:9.7.0
    environment:
      - CYPRESS_BROWSER=firefox
    volumes:
      - ./:/e2e
    working_dir: /e2e
    entrypoint: ["npx", "cypress", "run", "--browser", "firefox"]
