name: Run tests and publish report
on: [push]
jobs:
 test-cypress-papernest:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v3

     - name: Set up Docker Compose
       run: sudo apt-get update && sudo apt-get install -y docker-compose

     - name: Build and run Cypress tests using Docker Compose
       run: docker-compose up --abort-on-container-exit

     - name: Display logs for Cypress Chrome
       if: failure()
       run: docker-compose logs cypress-chrome

     - name: Display logs for Cypress Firefox
       if: failure()
       run: docker-compose logs cypress-firefox

     - name: Shutdown Docker Compose
       if: always()
       run: docker-compose down

     - name: Load test report history
       uses: actions/checkout@v3
       if: always()
       continue-on-error: true
       with:
         ref: gh-pages
         path: gh-pages

     - name: Build test report
       uses: simple-elf/allure-report-action@v1.7
       if: always()
       id: allure-report
       with:
         gh_pages: gh-pages
         allure_report: allure-report
         allure_history: allure-history
         allure_results: allure-results

     - name: Publish test report
       uses: peaceiris/actions-gh-pages@v3
       if: always()
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_branch: gh-pages
         publish_dir: allure-history