name: Run tests and publish report

on: [push]

jobs:
  test-cypress-papernest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, edge, firefox]

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress Test on ${{ matrix.browser }}
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          command: npx cypress run --browser ${{ matrix.browser }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results-${{ matrix.browser }}
          path: allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        id: allure-report
        with:
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report